DROP EXTENSION pg_net;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;
CREATE TABLE public.feature_requests (id uuid DEFAULT gen_random_uuid() NOT NULL, title text NOT NULL, description text NOT NULL, email text, votes integer DEFAULT 0, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.feature_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feature_requests ADD CONSTRAINT feature_requests_pkey PRIMARY KEY (id);
GRANT ALL ON public.feature_requests TO anon;
GRANT ALL ON public.feature_requests TO authenticated;
GRANT ALL ON public.feature_requests TO service_role;
CREATE POLICY "Anyone can submit feature request" ON public.feature_requests FOR INSERT TO anon WITH CHECK (true);
CREATE TABLE public.feedback (id uuid DEFAULT gen_random_uuid() NOT NULL, email text, message text NOT NULL, rating integer, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);
ALTER TABLE public.feedback ADD CONSTRAINT feedback_rating_check CHECK (rating >= 1 AND rating <= 5);
GRANT ALL ON public.feedback TO anon;
GRANT ALL ON public.feedback TO authenticated;
GRANT ALL ON public.feedback TO service_role;
CREATE POLICY "Anyone can submit feedback" ON public.feedback FOR INSERT TO anon WITH CHECK (true);
CREATE TABLE public.plugin_downloads (id uuid DEFAULT gen_random_uuid() NOT NULL, version text NOT NULL, downloaded_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.plugin_downloads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plugin_downloads ADD CONSTRAINT plugin_downloads_pkey PRIMARY KEY (id);
GRANT ALL ON public.plugin_downloads TO anon;
GRANT ALL ON public.plugin_downloads TO authenticated;
GRANT ALL ON public.plugin_downloads TO service_role;
CREATE POLICY "Anyone can track download" ON public.plugin_downloads FOR INSERT TO anon WITH CHECK (true);
